name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Docker Log In
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u twokims --password-stdin

      - name: Build Docker Image
        run: docker build -t twokims/cnmf-tools:latest -f ./Dockerfile .

      - name: Push Docker Image to Registry
        run: docker push twokims/cnmf-tools:latest
